# Generated by Django 5.2.5 on 2025-09-02 10:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='رمز العملة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العملة')),
                ('symbol', models.CharField(max_length=5, verbose_name='رمز العملة')),
                ('is_default', models.BooleanField(default=False, verbose_name='العملة الافتراضية')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_negative_wallet', models.BooleanField(default=False, verbose_name='السماح بالرصيد السالب للمحافظ')),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='حد الائتمان الافتراضي')),
                ('auto_generate_voucher_numbers', models.BooleanField(default=True, verbose_name='توليد أرقام السندات تلقائياً')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='VoucherSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('RECEIPT', 'سند قبض'), ('PAYMENT', 'سند صرف'), ('PURCHASE', 'فاتورة شراء'), ('EXPENSE', 'مصروف')], max_length=20, verbose_name='نوع السند')),
                ('prefix', models.CharField(max_length=10, verbose_name='البادئة')),
                ('next_number', models.IntegerField(default=1, verbose_name='الرقم التالي')),
                ('year', models.IntegerField(verbose_name='السنة')),
            ],
            options={
                'verbose_name': 'تسلسل السندات',
                'verbose_name_plural': 'تسلسلات السندات',
            },
        ),
    ]
