# Generated by Django 5.2.5 on 2025-09-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersequence',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع'),
        ),
        migrations.AlterUniqueTogether(
            name='vouchersequence',
            unique_together={('voucher_type', 'project', 'year')},
        ),
    ]
