# Generated by Django 5.2.5 on 2025-09-02 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشريك')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الحصة %')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='رصيد المحفظة')),
                ('carry_forward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد المرحّل')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='حد الائتمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='الشريك')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'شريك مشروع',
                'verbose_name_plural': 'شركاء المشروعات',
                'ordering': ['project', '-share_pct'],
                'unique_together': {('project', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='WalletPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_partner_ids', models.JSONField(default=list, verbose_name='ترتيب الشركاء')),
                ('allow_negative', models.BooleanField(default=False, verbose_name='السماح بالرصيد السالب')),
                ('credit_limit_per_partner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='حد الائتمان لكل شريك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_priority', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'أولوية الخصم',
                'verbose_name_plural': 'أولويات الخصم',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند صرف')], max_length=10, verbose_name='نوع السند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('ref_no', models.CharField(max_length=50, verbose_name='رقم السند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vouchers/', verbose_name='المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='أنشأ بواسطة')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='الشريك')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
                ('project_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='partners.projectpartner', verbose_name='محفظة الشريك')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'السندات',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('project', 'ref_no')},
            },
        ),
    ]
