# Generated by Django 5.2.5 on 2025-09-02 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('category', models.CharField(choices=[('labor', 'عمالة'), ('transport', 'نقل'), ('utilities', 'مرافق'), ('rent', 'إيجار'), ('maintenance', 'صيانة'), ('admin', 'إدارية'), ('materials', 'مواد'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الفئة')),
                ('description', models.TextField(verbose_name='البيان')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=10, verbose_name='التكرار')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('next_date', models.DateField(verbose_name='التاريخ التالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_generated', models.DateField(blank=True, null=True, verbose_name='آخر توليد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.stage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'مصروف دوري',
                'verbose_name_plural': 'المصروفات الدورية',
                'ordering': ['next_date', 'project'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('category', models.CharField(choices=[('labor', 'عمالة'), ('transport', 'نقل'), ('utilities', 'مرافق'), ('rent', 'إيجار'), ('maintenance', 'صيانة'), ('admin', 'إدارية'), ('materials', 'مواد'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الفئة')),
                ('payee_type', models.CharField(choices=[('supplier', 'مورد'), ('partner', 'شريك'), ('stock', 'صرف مواد'), ('employee', 'موظف'), ('contractor', 'مقاول'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستفيد')),
                ('payee_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المستفيد')),
                ('payee_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المستفيد')),
                ('description', models.TextField(verbose_name='البيان')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='المرفق')),
                ('is_allocated', models.BooleanField(default=False, verbose_name='تم التوزيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='أنشأ بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.stage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'date'], name='expenses_ex_project_456f60_idx'), models.Index(fields=['stage', 'is_allocated'], name='expenses_ex_stage_i_9feb2c_idx'), models.Index(fields=['payee_type', 'payee_id'], name='expenses_ex_payee_t_7a994b_idx')],
            },
        ),
    ]
