# Generated by Django 5.2.5 on 2025-09-02 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة صنف',
                'verbose_name_plural': 'فئات الأصناف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='كود الصنف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('uom', models.CharField(choices=[('PC', 'قطعة'), ('KG', 'كيلوجرام'), ('TON', 'طن'), ('M', 'متر'), ('M2', 'متر مربع'), ('M3', 'متر مكعب'), ('L', 'لتر'), ('BOX', 'كرتونة'), ('PACK', 'عبوة')], default='PC', max_length=10, verbose_name='وحدة القياس')),
                ('std_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='التكلفة القياسية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='الحد الأدنى للمخزون')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='الحد الأقصى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_in', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='الكمية الواردة')),
                ('qty_out', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='الكمية الصادرة')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='تكلفة الوحدة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='القيمة')),
                ('ref_type', models.CharField(choices=[('PI', 'فاتورة شراء'), ('ISSUE', 'صرف مواد'), ('ADJUST', 'تسوية'), ('TRANSFER', 'تحويل'), ('RETURN', 'مرتجع')], max_length=10, verbose_name='نوع المرجع')),
                ('ref_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('move_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='أنشأ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_moves', to='inventory.item', verbose_name='الصنف')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.stage', verbose_name='المرحلة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-move_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'item', 'move_date'], name='inventory_s_project_782c1e_idx'), models.Index(fields=['warehouse', 'item'], name='inventory_s_warehou_769ab9_idx'), models.Index(fields=['ref_type', 'ref_id'], name='inventory_s_ref_typ_e0ec78_idx')],
            },
        ),
    ]
