# Generated by Django 5.2.5 on 2025-09-02 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSettleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField(verbose_name='تاريخ القطع')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('posted', 'مرحّلة'), ('reversed', 'معكوسة')], default='open', max_length=10, verbose_name='الحالة')),
                ('total_cost_until_cutoff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي التكلفة حتى تاريخ القطع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ العكس')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='أنشأ بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'دفعة تسوية',
                'verbose_name_plural': 'دفعات التسوية',
                'ordering': ['-cutoff_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('settled', 'مسددة'), ('void', 'ملغاة')], default='pending', max_length=10, verbose_name='الحالة')),
                ('settled_voucher_id', models.IntegerField(blank=True, null=True, verbose_name='رقم سند التسديد')),
                ('settled_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسديد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('from_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_from', to='partners.partner', verbose_name='من الشريك (المدين)')),
                ('to_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_to', to='partners.partner', verbose_name='إلى الشريك (الدائن)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='settlements.partnersettlebatch', verbose_name='دفعة التسوية')),
            ],
            options={
                'verbose_name': 'مطالبة',
                'verbose_name_plural': 'المطالبات',
                'ordering': ['batch', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSettleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_pct_at_cutoff', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الحصة عند القطع %')),
                ('should_bear', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ما يجب تحمله')),
                ('actually_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ما تم دفعه فعلاً')),
                ('diff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الفرق')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='settlements.partnersettlebatch', verbose_name='دفعة التسوية')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='الشريك')),
                ('project_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.projectpartner', verbose_name='محفظة الشريك')),
            ],
            options={
                'verbose_name': 'سطر تسوية',
                'verbose_name_plural': 'سطور التسوية',
                'ordering': ['batch', '-diff'],
            },
        ),
        migrations.AddIndex(
            model_name='partnersettlebatch',
            index=models.Index(fields=['project', 'cutoff_date'], name='settlements_project_653fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='partnersettlebatch',
            index=models.Index(fields=['status'], name='settlements_status_213ea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnersettleline',
            unique_together={('batch', 'partner')},
        ),
    ]
