# Generated by Django 5.2.5 on 2025-09-02 10:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('by_share', 'حسب الحصة'), ('custom', 'مخصص')], default='by_share', max_length=10, verbose_name='قاعدة التوزيع')),
                ('details_json', models.JSONField(default=dict, verbose_name='تفاصيل التوزيع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ الإجمالي')),
                ('posted', models.BooleanField(default=False, verbose_name='مرحّل')),
                ('alloc_date', models.DateField(verbose_name='تاريخ التوزيع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'توزيع تكاليف',
                'verbose_name_plural': 'توزيعات التكاليف',
                'ordering': ['-alloc_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ')),
                ('share_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الحصة %')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سطر توزيع',
                'verbose_name_plural': 'سطور التوزيع',
                'ordering': ['allocation', '-amount'],
            },
        ),
    ]
