# Generated by Django 5.2.5 on 2025-09-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('partners', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.stage', verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='allocationline',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='allocations.allocation', verbose_name='التوزيع'),
        ),
        migrations.AddField(
            model_name='allocationline',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='الشريك'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['project', 'stage', 'posted'], name='allocations_project_7e5f78_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['alloc_date'], name='allocations_alloc_d_d9e020_idx'),
        ),
    ]
